config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :posts

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        tables: true,
        link_attributes: {rel: 'nofollow', target: "_blank"}
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fabio Nisci - Part Designer, Part Developer</title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id="main_navigation" class="clearfix">
    <%= link_to "Home", root_path, class: "name" %>
    <nav>
      <%= link_to "Articles", posts_path %>
      <%= link_to "Projects", projects_path %>
      <%#= link_to "Contact", new_contact_path %>
      <% # if user_signed_in? %>
          <%#= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% # end %>
    </nav>
  </header>

  <% if notice %>
      <p class="notice"><%= notice %></p>
  <% elsif alert %>
      <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  <footer id="main_footer">
    <p class="copyright">&copy;2015 Fabio Nisci</p>
    <nav>
      <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="https://bitbucket.org/fabiosoft/" target="_blank"><i class="fa fa-bitbucket"></i></a>
    </nav>
  </footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title %>

    <br>
    <br>

    <%= f.label :content, "Write your article here" %><br>
    <%= f.text_area :content %>

    <br>
    <br>

    <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
  <% # if user_signed_in? %>
  <div id="admin_links">
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
  </div>
  <% #end %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>
<div id="posts_wrapper" class="skinny_wrapper">
  <% # if user_signed_in? %>
  <div id="admin_links">
    <%= link_to 'New Post', new_post_path %>
  </div>
  <% #end %>
  <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <hr>
      </div>
  <% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>

  <div id="admin_links">
    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @post.content %>
    <%#= simple_format @post.content %>
  </div>

  <% # if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit Article", edit_post_path(@post) %>
        <%= link_to "Delete Article", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
  <% #end %>

  <hr>

  <div id="share_box">
    <p>Share The DO List</p>
    <!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @username - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
  </div>

  <hr>

  <%#= render 'disqus' %>

</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <%= f.label :title %><br>
    <%= f.text_field :title %>

    <br>
    <br>

    <%= f.label :content, "Describe your project here" %><br>
    <%= f.text_area :content %>

    <br>
    <br>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
  <div id="admin_links">
    <%= link_to 'Show', @project %> |
    <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <div id="admin_links">
    <%= link_to 'New Project', new_project_path %>
    </div>
  <% @projects.each do |project| %>
      <div class="post">
        <p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
        <h2><a href="#"><%= link_to project.title, project %></a></h2>
        <hr>
      </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>

  <div id="admin_links">
  <%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @project.content %>

    <div class="button_wrapper">
      <!--<a href="<%#= @project.link %>" class="project_button" target="_blank">Visit <%#= @project.title %></a>-->
    </div>
  </div>

  <%# if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_project_path(@project) %>
        <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
  <%# end %>

  <hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col-1 about homepage_content">
    <h2>About</h2>
    <hr>
    <p>I'm a designer &amp; developer living in Italy.</p>
    <p>You can find me speaking on <a href = "mailto:staff@fabiosoft.com">email</a>, and sharing some code on <a href="https://bitbucket.org/fabiosoft/" target="_blank">Bitbucket</a>.</p>
    <p>Esperienza nella progettazione e sviluppo di <b>Applicazioni mobili</b>. Integro le conoscenze acquisite in ambito accademico con un continuo studio di nuove tecnologie che mi permettano di creare applicazioni sempre più affidabili sicure ed efficienti. Capacità di lavorare in gruppo e ottima conoscenza di sistemi iOS. Buon intuito e abilità nel <b>trovare soluzioni</b> ideali ai problemi risultanti dalle specifiche dei progetti.</p>
  </div>
  <div class="col-2 homepage_content">
    <h2>Stuff I've Written</h2>
    <hr>
    <% @posts.each do |post| %>
        <h3><a href="#"><%= link_to post.title, post %></a></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>
  <div class="col-3 homepage_content">
    <h2>Stuff I've Built</h2>
    <hr>
    <% @projects.each do |project| %>
        <h3><a href="#"><%= link_to project.title, project %></a></h3>
        <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>
</div>